In [35]:
import pandas as pd
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import StandardScaler

In [36]:
df = pd.read_csv('../data/train_data_wo_outliers_full_1.csv')
df

,weight,quality,color,clarity,depth_percent,table_percent,price,volume
0,0.30,Premium,D,SI2,0.624,0.58,6.353,49.437424
1,1.01,Ideal,E,VVS2,0.627,0.56,9.183,167.551728
2,0.72,Ideal,F,VS2,0.618,0.59,7.983,116.024916
3,1.08,Very Good,G,SI2,0.632,0.57,8.371,175.141200
4,0.36,Premium,G,VS1,0.623,0.59,6.588,57.739500
...,...,...,...,...,...,...,...,...
36939,0.42,Premium,D,SI2,0.621,0.59,6.551,68.658008
36940,0.53,Premium,G,VS2,0.620,0.58,7.382,86.900716
36941,0.80,Good,G,SI2,0.628,0.58,7.768,127.578060
36942,1.01,Very Good,F,VS2,0.615,0.57,8.726,164.229120
36943,1.30,Premium,I,VS2,0.601,0.58,8.771,216.970320

In [37]:
#encoding categorical variables
mapping = {'quality':['Fair', 'Good', 'Very Good', 'Premium', 'Ideal'], 
            'color':['J', 'I', 'H', 'G', 'F', 'E', 'D'],
            'clarity':['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF']}
for k,v in mapping.items():
    for i in v:
        df[k] = df[k].replace(i, v.index(i))
df

,weight,quality,color,clarity,depth_percent,table_percent,price,volume
0,0.30,3,6,1,0.624,0.58,6.353,49.437424
1,1.01,4,5,5,0.627,0.56,9.183,167.551728
2,0.72,4,4,3,0.618,0.59,7.983,116.024916
3,1.08,2,3,1,0.632,0.57,8.371,175.141200
4,0.36,3,3,4,0.623,0.59,6.588,57.739500
...,...,...,...,...,...,...,...,...
36939,0.42,3,6,1,0.621,0.59,6.551,68.658008
36940,0.53,3,3,3,0.620,0.58,7.382,86.900716
36941,0.80,1,3,1,0.628,0.58,7.768,127.578060
36942,1.01,2,4,3,0.615,0.57,8.726,164.229120
36943,1.30,3,1,3,0.601,0.58,8.771,216.970320

In [38]:
#dummies for nominal variables
#dummies = pd.get_dummies(df[['quality', 'color', 'clarity']], prefix_sep = "_", prefix = ['quality_EN', 'color_EN', 'clarity_EN'], dtype = int)
#df = pd.concat([df, dummies], axis = 1).drop(['quality', 'color', 'clarity'], axis = 1)
#df

In [39]:
#standardizing the data robust
robust = RobustScaler()
robust.fit(df[["weight", "depth_percent", "table_percent", "volume"]])
X_robust = robust.transform(df[["weight", "depth_percent", "table_percent", "volume"]])
df[["weight_ES", "depth_percent_ES", "table_percent_ES", "volume_ES"]] = X_robust
df.drop(["weight", "depth_percent", "table_percent", "volume"], axis=1, inplace=True)
df.head()

,quality,color,clarity,price,weight_ES,depth_percent_ES,table_percent_ES,volume_ES
0,3,6,1,6.353,-0.625000,0.357143,0.333333,-0.591767
1,4,5,5,9.183,0.484375,0.571429,-0.333333,0.550637
2,4,4,3,7.983,0.031250,-0.071429,0.666667,0.052269
3,2,3,1,8.371,0.593750,0.928571,0.000000,0.624043
4,3,3,4,6.588,-0.531250,0.285714,0.666667,-0.511469

In [40]:
#standardizing the data standard
#scaler = StandardScaler()
#scaler.fit(df[["weight", "depth_percent", "table_percent", "volume"]])
#X_scaled = scaler.transform(df[["weight", "depth_percent", "table_percent", "volume"]])
#df[["weight_ES", "depth_percent_ES", "table_percent_ES", "volume_ES"]] = X_scaled
#df.drop(["weight", "depth_percent", "table_percent", "volume"], axis=1, inplace=True)
#df.head()

In [41]:
df.to_csv('../data/train_data_encoded_full_1.csv', index=False)