In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/train_data_wo_outliers_full.csv')
df

       weight    quality color clarity  table_percent     price  depth_percent
0        0.30    Premium     D     SI2           0.58  1.848927          0.624
1        1.01      Ideal     E    VVS2           0.56  2.217354          0.627
2        0.72      Ideal     F     VS2           0.59  2.077314          0.618
3        1.08  Very Good     G     SI2           0.57  2.124773          0.632
4        0.36    Premium     G     VS1           0.59  1.885250          0.623
...       ...        ...   ...     ...            ...       ...            ...
39824    0.42    Premium     D     SI2           0.59  1.879618          0.621
39825    0.53    Premium     G     VS2           0.58  1.999045          0.620
39826    0.80       Good     G     SI2           0.58  2.050013          0.628
39827    1.01  Very Good     F     VS2           0.57  2.166307          0.615
39828    1.30    Premium     I     VS2           0.58  2.171451          0.601

[39829 rows x 7 columns]

In [3]:
#encoding categorical variables
mapping = {'quality':['Fair', 'Good', 'Very Good', 'Premium', 'Ideal'], 
            'color':['J', 'I', 'H', 'G', 'F', 'E', 'D'],
            'clarity':['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF']}
for k,v in mapping.items():
    for i in v:
        df[k] = df[k].replace(i, v.index(i))
df

       weight  quality  color  clarity  table_percent     price  depth_percent
0        0.30        3      6        1           0.58  1.848927          0.624
1        1.01        4      5        5           0.56  2.217354          0.627
2        0.72        4      4        3           0.59  2.077314          0.618
3        1.08        2      3        1           0.57  2.124773          0.632
4        0.36        3      3        4           0.59  1.885250          0.623
...       ...      ...    ...      ...            ...       ...            ...
39824    0.42        3      6        1           0.59  1.879618          0.621
39825    0.53        3      3        3           0.58  1.999045          0.620
39826    0.80        1      3        1           0.58  2.050013          0.628
39827    1.01        2      4        3           0.57  2.166307          0.615
39828    1.30        3      1        3           0.58  2.171451          0.601

[39829 rows x 7 columns]

In [4]:
df.to_csv('../data/train_data_encoded_full.csv', index=False)