In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/test_data_cleaned.csv')
df

       weight    quality color clarity  table_percent  depth_percent
0        0.32      Ideal     I     SI1          0.580          0.605
1        1.24    Premium     I     SI1          0.600          0.629
2        1.66    Premium     D     SI1          0.590          0.620
3        0.75    Premium     D     SI2          0.560          0.606
4        1.50       Fair     E     SI2          0.550          0.648
...       ...        ...   ...     ...            ...            ...
13480    1.10    Premium     G     SI1          0.600          0.596
13481    0.90  Very Good     D     SI1          0.600          0.621
13482    0.30      Ideal     F     VS2          0.533          0.621
13483    1.25      Ideal     I     SI1          0.590          0.596
13484    0.81    Premium     F     SI1          0.580          0.616

[13485 rows x 6 columns]

In [3]:
#encoding categorical variables
mapping = {'quality':['Fair', 'Good', 'Very Good', 'Premium', 'Ideal'], 
            'color':['J', 'I', 'H', 'G', 'F', 'E', 'D'],
            'clarity':['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF']}
for k,v in mapping.items():
    for i in v:
        df[k] = df[k].replace(i, v.index(i))
df

       weight  quality  color  clarity  table_percent  depth_percent
0        0.32        4      1        2          0.580          0.605
1        1.24        3      1        2          0.600          0.629
2        1.66        3      6        2          0.590          0.620
3        0.75        3      6        1          0.560          0.606
4        1.50        0      5        1          0.550          0.648
...       ...      ...    ...      ...            ...            ...
13480    1.10        3      3        2          0.600          0.596
13481    0.90        2      6        2          0.600          0.621
13482    0.30        4      4        3          0.533          0.621
13483    1.25        4      1        2          0.590          0.596
13484    0.81        3      4        2          0.580          0.616

[13485 rows x 6 columns]

In [4]:
df.to_csv('../data/test_data_encoded.csv', index=False)